# -*- encoding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView
from ag.gestion import views

urlpatterns = [
    url(r'^$', views.tableau_de_bord_view, name='tableau_de_bord'),
    url(r'^regles$',  TemplateView.as_view(template_name='gestion/regles.html'),
        name='regles'),
    url(r'^liste_etablissements_json/$', views.liste_etablissements_json,
        name='liste_etablissements_json'),
    url(r'^participants/$', views.participants_view, name='participants'),
    url(r'^participants/(\d+)/fiche/$', views.fiche_participant,
        name='fiche_participant'),
    url(r'^participants/(\d+)/renseignements-personnels/$',
        views.renseignements_personnels_view,
        name='renseignements_personnels'),
    url(r'^participants/(\d+)/sejour/$', views.sejour,
        name='sejour'),
    url(r'^participants/(\d+)/notes-de-frais/$', views.notes_de_frais,
        name='notes_de_frais'),
    url(r'^participants/(\d+)/suivi/$', views.suivi_view,
        name='suivi'),
    url(r'^participants/(\d+)/transport/$', views.transport,
        name='transport'),
    url(r'^participants/(\d+)/invites/$', views.invites_view,
        name='invites'),
    url(r'^participants/(\d+)/facturation/$', views.facturation,
        name='facturation'),
    url(r'^participants/(\d+)/fichiers/$', views.fichiers_view,
        name='fichiers'),
    url(r'^media_participant/(?P<nom_fichier>.*)$', views.media_participant,
        name='media_participant'),
    url(r'^participants/(\d+)/facture.pdf$', views.facture_pdf,
        name='facture_pdf'),
    url(r'^participants/(\d+)/itineraire.pdf$', views.itineraire_pdf,
        name='itineraire_pdf'),
    url(r'^participants/nouveau/$', views.ajout_participant,
        name='ajout_participant'),
    url(r'^participants/supprimer/$', views.supprimer_participant,
        name='supprimer_participant'),
    url(r'^volgroupe/nouveau/$', views.ajouter_vol_groupe,
        name='ajouter_vol_groupe'),
    url(r'^volgroupe/supprimer/(\d+)/$', views.supprimer_vol_groupe,
        name='supprimer_vol_groupe'),
    url(r'^volgroupe/(\d+)/$', views.modifier_vol_groupe,
        name='modifier_vol_groupe'),
    url(r'^volgroupe/$', views.liste_vols_groupes,
        name='liste_vols_groupes'),
    url(r'^etats_listes/$', views.etats_listes, name='etats_listes'),
    url(r'^etat_inscrits/$', views.etat_inscrits, name='etat_inscrits'),
    url(r'^etat_activites/$', views.etat_activites, name='etat_activites'),
    url(r'^etat_votants/$', views.etat_votants, name='etat_votants'),
    url(r'^votants_csv/$', views.votants_csv, name='votants_csv'),
    url(r'^etat_arrivees_departs/$', views.etat_arrivees_departs,
        name='etat_arrivees_departs'),
    url(r'^etat_vols/$', views.etat_vols, name='etat_vols'),
    url(r'^etat_vols.csv$', views.etat_vols_csv, name='etat_vols_csv'),
    url(r'^export_donnees_csv$', views.export_donnees_csv,
        name='export_donnees_csv'),
    url(r'^itineraire/(\d+)/$', views.itineraire_view,
        name='itineraire'),
    url(r'^etat_paiements/$', views.etat_paiements, name='etat_paiements'),
    url(r'^etat_paiements_csv/$', views.etat_paiements_csv,
        name='etat_paiements_csv'),
    url(r'^liste_coupons/$', views.liste_coupons, name='liste_coupons'),
    url(r'^listes_hotels/$', views.listes_hotels, name='liste_hotels'),
    url(r'logout/$', views.logout, name='logout'),
    url(r'motdepasse/$', views.changement_mot_de_passe,
        name='changement_mot_de_passe'),
    url(r'activites_scientifiques/$',
        views.liste_participants_activites_scientifiques,
        name='liste_participants_activites_scientifiques'),
    url(r'^coupon_transport/(\d+)/$', views.coupon_transport,
        name='coupon_transport'),
]