# -*- encoding: utf-8 -*-

from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from .views import (
    participants_view,
    suivi_view,
    renseignements_personnels_view,
    fichiers_view,
    invites_view,
    itineraire_view)

urlpatterns = patterns(
    'ag.gestion.views',
    url(r'^$', 'tableau_de_bord', name='tableau_de_bord'),
    url(r'^regles$',  TemplateView.as_view(template_name='gestion/regles.html'),
        name='regles'),
    url(r'^liste_etablissements_json/$', 'liste_etablissements_json',
        name='liste_etablissements_json'),
    url(r'^participants/$', participants_view, name='participants'),
    url(r'^participants/(\d+)/fiche/$', 'fiche_participant',
        name='fiche_participant'),
    url(r'^participants/(\d+)/renseignements-personnels/$',
        renseignements_personnels_view,
        name='renseignements_personnels'),
    url(r'^participants/(\d+)/sejour/$', 'sejour',
        name='sejour'),
    url(r'^participants/(\d+)/notes-de-frais/$', 'notes_de_frais',
        name='notes_de_frais'),
    url(r'^participants/(\d+)/suivi/$', suivi_view,
        name='suivi'),
    url(r'^participants/(\d+)/transport/$', 'transport',
        name='transport'),
    url(r'^participants/(\d+)/invites/$', invites_view,
        name='invites'),
    url(r'^participants/(\d+)/facturation/$', 'facturation',
        name='facturation'),
    url(r'^participants/(\d+)/fichiers/$', fichiers_view,
        name='fichiers'),
    url(r'^media_participant/(?P<nom_fichier>.*)$', 'media_participant',
        name='media_participant'),
    url(r'^participants/(\d+)/facture.pdf$', 'facture_pdf',
        name='facture_pdf'),
    url(r'^participants/(\d+)/itineraire.pdf$', 'itineraire_pdf',
        name='itineraire_pdf'),
    url(r'^participants/nouveau/$', 'ajout_participant',
        name='ajout_participant'),
    url(r'^participants/supprimer/$', 'supprimer_participant',
        name='supprimer_participant'),
    url(r'^volgroupe/nouveau/$', 'ajouter_vol_groupe',
        name='ajouter_vol_groupe'),
    url(r'^volgroupe/supprimer/(\d+)/$', 'supprimer_vol_groupe',
        name='supprimer_vol_groupe'),
    url(r'^volgroupe/(\d+)/$', 'modifier_vol_groupe',
        name='modifier_vol_groupe'),
    url(r'^volgroupe/$', 'liste_vols_groupes',
        name='liste_vols_groupes'),
    url(r'^etats_listes/$', 'etats_listes', name='etats_listes'),
    url(r'^etat_inscrits/$', 'etat_inscrits', name='etat_inscrits'),
    url(r'^etat_activites/$', 'etat_activites', name='etat_activites'),
    url(r'^etat_votants/$', 'etat_votants', name='etat_votants'),
    url(r'^votants_csv/$', 'votants_csv', name='votants_csv'),
    url(r'^etat_arrivees_departs/$', 'etat_arrivees_departs',
        name='etat_arrivees_departs'),
    url(r'^etat_vols/$', 'etat_vols', name='etat_vols'),
    url(r'^etat_vols.csv$', 'etat_vols_csv', name='etat_vols_csv'),
    url(r'^export_donnees_csv$', 'export_donnees_csv',
        name='export_donnees_csv'),
    url(r'^itineraire/(\d+)/$', itineraire_view,
        name='itineraire'),
    url(r'^etat_paiements/$', 'etat_paiements', name='etat_paiements'),
    url(r'^etat_paiements_csv/$', 'etat_paiements_csv',
        name='etat_paiements_csv'),
    url(r'logout/$', 'logout', name='logout'),
    url(r'motdepasse/$', 'changement_mot_de_passe',
        name='changement_mot_de_passe'),
    url(r'activites_scientifiques/$',
        'liste_participants_activites_scientifiques',
        name='liste_participants_activites_scientifiques'),
)
